### ISSUE TITLE
Basic auth with Curl

### ISSUE THREAD

**Issue by silveraignacio** [rodrigoluissilva/Zabbix-Apache-Status-Template#2]
Hi! I have several issues with Basci Auth with apache using your script. I could fix it addin the parameter -u followed by $APACHEUSER:$APACHEPASSWD in the curl line, because I think apache does not support the auth in the following way http://user:pass@url/

I can pull a request with the update if you want.
 
Following this issue on the side, the Script is very powerfull and also very usefull

**Comment by rodrigoluissilva** [comment]
Hi

Thanks for your suggestion, I applied the fix and now it's working with special characters using the -u/--user for curl and wget

Some special character will need to be escaped and quoted, such as $

--passwd='%P@\$\$0rd?'

if you get any other problem, feel free to contact me.

Cheers
