### ISSUE TITLE
Check Backend status

### ISSUE THREAD

**Issue by silveraignacio** [rodrigoluissilva/Zabbix-Apache-Status-Template#3]
Hi! Should be great that could be possible to check if some backend is down.

**Comment by rodrigoluissilva** [comment]
Actually, it does

if no information is get back from the Apache server, the script will send "**apache[failed]=1**" and there is a trigger "**[{HOST.NAME}] Fail collection Apache data**" to catch this information and alert you.

**Comment by silveraignacio** [comment]
Hi! This is not what I'm looking for. I reffer to Backend as a Backend of Reverse Proxy, more likely a Balancer Member of a Virtual host.
Is more clear now?
Thanks!

**Comment by rodrigoluissilva** [comment]
Hi Silvera,

It's clear now, but it's out of the scope of this template.

The reverse proxy keeps the backends hidden from the real world, so to check the backend health you have to set all of them on Zabbix or build a template with an auto discovery rules to find them.

I'll close this issue, but thanks for your suggestion.
