### ISSUE TITLE
Failed Sender

### ISSUE THREAD

**Issue by AdrianLince** [rodrigoluissilva/Zabbix-Apache-Status-Template#4]
Al ejecutar ./zbxApacheStatusCheck --host=200.32.40.81 --zabbixsource ="200.32.40.81" --zabbixserver=192.168.0.216 -d
 siempre falla
zabbix_sender output

info from server: "processed: 0; failed: 28; total: 28; seconds spent: 0.000321"
sent: 28; skipped: 0; total: 28

Please

**Comment by rodrigoluissilva** [comment]
Hi Adrian,

There is not much information in your message, but you can try running this command and see if you can get the server-status result

curl --insecure --max-time 30 --silent --location -H "Cache-Control: no-cache" "http://200.32.40.81:80/server-status?auto"

the option --zabbixsource has a space before the equal sign

Regards

**Comment by AdrianLince** [comment]
Hi Rodrigo. 
Si ejecuto el comnado me da este resultado
Total Accesses: 24128
Total kBytes: 35548
CPULoad: .060592
Uptime: 188127
ReqPerSec: .128254
BytesPerSec: 193.492
BytesPerReq: 1508.67
BusyWorkers: 3
IdleWorkers: 15
Scoreboard: _________K____W__K..............................................................................................................................................................................................................................................

Corregi el espacio despues de zabbixsource y aun continua el error.

**Comment by AdrianLince** [comment]
Version de Zabbix_Server 3.2.11, zabbix_agent 3.2.11 y zabbix_Sender 3.2.11

**Comment by rodrigoluissilva** [comment]
the parameter --zabbixsource has to be equal to the Host name used in your Zabbix
are you using the IP 200.32.40.81 has the Hostname?

**Comment by AdrianLince** [comment]
Thank you very much, that was the problem. Sorry
