### ISSUE TITLE
No data in graph 

### ISSUE THREAD

**Issue by ObiJonKenobi89** [rodrigoluissilva/Zabbix-Apache-Status-Template#8]
Hi guys

Environment: 

Target host: 
CentOS Linux release 7.6.1810 (Core)
Server version: Apache/2.4.6 (CentOS)
Server built:   Jul 29 2019 17:18:49

zbxApacheStatusCheck is being ran from the Zabbix server. Values: 

# Define some default values
HOST=[IP of server I'm monitoring]
PORT=80
PROTO=http
ZABBIXSERVER=localhost
SENDER=/usr/bin/zabbix_sender
DEBUG=0
TEST=0
ZABBIXPORT=10051
ZABBIXSOURCE=[Hostname of server as written in Zabbix]
TIMEOUT=30
DEFAULTCONFIG="ServerVersion
Total Accesses
Total kBytes
CPULoad
CPUSystem
CPUUser
Load1
Load5
Load15
Uptime
ReqPerSec
BytesPerSec
BytesPerReq
BusyWorkers
IdleWorkers
Scoreboard"

Crontab: 

* * * * * root /etc/zabbix/scripts/zbxApacheStatusCheck -d -t --host=[IP address of host I'm monitoring] --zabbixsource="[Hostname as described in Zabbix]" --zabbixserver=localhost

But the graphs in Zabbix are blank. Other graphs from other template are showing data. Where am I going wrong? 

EDIT: For the avoidance of doubt, I can see the server-status page when I links from the Zabbix box to the box I want to monitor. http://server.name/server-status and /server-status?auto function as expected.

**Comment by ObiJonKenobi89** [comment]
#UPDATE

Looking at /var/log/cron I see that a connection is occurring, the stats are being collated but are still failing to send: 


Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (########################################)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (Metrics to be send)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  SERVER                METRIC                                        VALUE)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[failed]                         0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[ServerVersion]                  0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Total Accesses]                 207)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Total kBytes]                   1215)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[CPULoad]                        .145299)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[CPUSystem]                      0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[CPUUser]                        0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Load1]                          0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Load5]                          0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Load15]                         0)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Uptime]                         1521)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[ReqPerSec]                      .136095)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[BytesPerSec]                    817.988)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[BytesPerReq]                    6010.43)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[BusyWorkers]                    1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[IdleWorkers]                    5)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[WaitingForConnection]           6)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[StartingUp]                     1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[ReadingRequest]                 1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[SendingReply]                   2)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[KeepAlive]                      1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[DNSLookup]                      1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[ClosingConnection]              1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[Logging]                        1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[GracefullyFinishing]            1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[IdleCleanupOfWorker]            1)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[OpenSlotWithNoCurrentProcess]   251)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (  OTL-CROSSRAIL-DEV     custom.apache[TotalWorkers]                   256)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (########################################)

[Parameters] 

Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (Command line to send data to Zabbix)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (/usr/bin/zabbix_sender -v --zabbix-server 127.0.0.1 --port 10051 --input-file /tmp/tmp.QjPj9RSwVR)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (########################################)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT (zabbix_sender output)
Sep  3 09:26:02 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:11 id83585 CROND[8949]: (root) CMDOUT (Sending failed. Use option -vv for more detailed output.)
Sep  3 09:26:11 id83585 CROND[8949]: (root) CMDOUT ()
Sep  3 09:26:11 id83585 CROND[8949]: (root) CMDOUT ()


zabbix_server.log also shows: 


  7117:20190903:092001.811 trapper got '{"request":"sender data","data":[{"host":"OTL-CROSSRAIL-DEV","key":"custom.apache[failed]","value":"0"},{"host":"OTL-CROSSRAIL-DEV","key":"custom.apache[ServerVersion]$
  7117:20190903:092001.811 In recv_senderhistory()
  7117:20190903:092001.812 In process_client_history_data()
  7117:20190903:092001.812 In parse_history_data()
  7117:20190903:092001.812 End of parse_history_data():SUCCEED processed:28/28
  7117:20190903:092001.812 In process_history_data()
  7117:20190903:092001.812 End of process_history_data() processed:0
  7117:20190903:092001.812 End of process_client_history_data():SUCCEED
  7117:20190903:092001.812 In zbx_send_response_ext()
  7117:20190903:092001.812 zbx_send_response_ext() '{"response":"success","info":"processed: 0; failed: 28; total: 28; seconds spent: 0.000464"}'
  7117:20190903:092001.812 End of zbx_send_response_ext():SUCCEED
  7117:20190903:092001.812 End of recv_senderhistory()


What could be causing this?

**Comment by rodrigoluissilva** [comment]
Hi ObiJonKenobi89,

You are using -d and -t in your crontab.
The -t option is for test only and don't send any data.
Remove it and try again

Regards
